default:
  image: node

cache:
  paths:
    - backend/node_modules/
    - backend/src/generated/

stages:
  - install
  - lint
  - build

install:
  stage: install
  script:
    - cd backend
    - npm ci

lint:
  stage: lint
  script:
    - cd backend
    - npm run lint

build:
  stage: build
  script:
    - cd backend
    - export DATABASE_URL="postgresql://fake:fake@localhost:5432/fake"
    - npx prisma generate
    - npm run build